import { Keymap } from '../types';

export const en: Keymap = {
  // Первый ряд (цифры)
  '1': { key: '1', code: 'Digit1', keyCode: 49 },
  '2': { key: '2', code: 'Digit2', keyCode: 50 },
  '3': { key: '3', code: 'Digit3', keyCode: 51 },
  '4': { key: '4', code: 'Digit4', keyCode: 52 },
  '5': { key: '5', code: 'Digit5', keyCode: 53 },
  '6': { key: '6', code: 'Digit6', keyCode: 54 },
  '7': { key: '7', code: 'Digit7', keyCode: 55 },
  '8': { key: '8', code: 'Digit8', keyCode: 56 },
  '9': { key: '9', code: 'Digit9', keyCode: 57 },
  '0': { key: '0', code: 'Digit0', keyCode: 48 },
  '-': { key: '-', code: 'Minus', keyCode: 189 },
  '=': { key: '=', code: 'Equal', keyCode: 187 },

  // Второй ряд (QWERTY)
  'q': { key: 'q', code: 'KeyQ', keyCode: 81 },
  'w': { key: 'w', code: 'KeyW', keyCode: 87 },
  'e': { key: 'e', code: 'KeyE', keyCode: 69 },
  'r': { key: 'r', code: 'KeyR', keyCode: 82 },
  't': { key: 't', code: 'KeyT', keyCode: 84 },
  'y': { key: 'y', code: 'KeyY', keyCode: 89 },
  'u': { key: 'u', code: 'KeyU', keyCode: 85 },
  'i': { key: 'i', code: 'KeyI', keyCode: 73 },
  'o': { key: 'o', code: 'KeyO', keyCode: 79 },
  'p': { key: 'p', code: 'KeyP', keyCode: 80 },
  '[': { key: '[', code: 'BracketLeft', keyCode: 219 },
  ']': { key: ']', code: 'BracketRight', keyCode: 221 },

  // Третий ряд (ASDF)
  'a': { key: 'a', code: 'KeyA', keyCode: 65 },
  's': { key: 's', code: 'KeyS', keyCode: 83 },
  'd': { key: 'd', code: 'KeyD', keyCode: 68 },
  'f': { key: 'f', code: 'KeyF', keyCode: 70 },
  'g': { key: 'g', code: 'KeyG', keyCode: 71 },
  'h': { key: 'h', code: 'KeyH', keyCode: 72 },
  'j': { key: 'j', code: 'KeyJ', keyCode: 74 },
  'k': { key: 'k', code: 'KeyK', keyCode: 75 },
  'l': { key: 'l', code: 'KeyL', keyCode: 76 },
  ';': { key: ';', code: 'Semicolon', keyCode: 186 },
  "'": { key: "'", code: 'Quote', keyCode: 222 },
  '\\': { key: '\\', code: 'Backslash', keyCode: 220 },

  // Четвертый ряд (ZXCV)
  'z': { key: 'z', code: 'KeyZ', keyCode: 90 },
  'x': { key: 'x', code: 'KeyX', keyCode: 88 },
  'c': { key: 'c', code: 'KeyC', keyCode: 67 },
  'v': { key: 'v', code: 'KeyV', keyCode: 86 },
  'b': { key: 'b', code: 'KeyB', keyCode: 66 },
  'n': { key: 'n', code: 'KeyN', keyCode: 78 },
  'm': { key: 'm', code: 'KeyM', keyCode: 77 },
  ',': { key: ',', code: 'Comma', keyCode: 188 },
  '.': { key: '.', code: 'Period', keyCode: 190 },
  '/': { key: '/', code: 'Slash', keyCode: 191 },

  // Заглавные буквы (с Shift)
  'Q': { key: 'Q', code: 'KeyQ', keyCode: 81, shiftKey: true },
  'W': { key: 'W', code: 'KeyW', keyCode: 87, shiftKey: true },
  'E': { key: 'E', code: 'KeyE', keyCode: 69, shiftKey: true },
  'R': { key: 'R', code: 'KeyR', keyCode: 82, shiftKey: true },
  'T': { key: 'T', code: 'KeyT', keyCode: 84, shiftKey: true },
  'Y': { key: 'Y', code: 'KeyY', keyCode: 89, shiftKey: true },
  'U': { key: 'U', code: 'KeyU', keyCode: 85, shiftKey: true },
  'I': { key: 'I', code: 'KeyI', keyCode: 73, shiftKey: true },
  'O': { key: 'O', code: 'KeyO', keyCode: 79, shiftKey: true },
  'P': { key: 'P', code: 'KeyP', keyCode: 80, shiftKey: true },
  'A': { key: 'A', code: 'KeyA', keyCode: 65, shiftKey: true },
  'S': { key: 'S', code: 'KeyS', keyCode: 83, shiftKey: true },
  'D': { key: 'D', code: 'KeyD', keyCode: 68, shiftKey: true },
  'F': { key: 'F', code: 'KeyF', keyCode: 70, shiftKey: true },
  'G': { key: 'G', code: 'KeyG', keyCode: 71, shiftKey: true },
  'H': { key: 'H', code: 'KeyH', keyCode: 72, shiftKey: true },
  'J': { key: 'J', code: 'KeyJ', keyCode: 74, shiftKey: true },
  'K': { key: 'K', code: 'KeyK', keyCode: 75, shiftKey: true },
  'L': { key: 'L', code: 'KeyL', keyCode: 76, shiftKey: true },
  'Z': { key: 'Z', code: 'KeyZ', keyCode: 90, shiftKey: true },
  'X': { key: 'X', code: 'KeyX', keyCode: 88, shiftKey: true },
  'C': { key: 'C', code: 'KeyC', keyCode: 67, shiftKey: true },
  'V': { key: 'V', code: 'KeyV', keyCode: 86, shiftKey: true },
  'B': { key: 'B', code: 'KeyB', keyCode: 66, shiftKey: true },
  'N': { key: 'N', code: 'KeyN', keyCode: 78, shiftKey: true },
  'M': { key: 'M', code: 'KeyM', keyCode: 77, shiftKey: true },

  // Символы с Shift
  '!': { key: '!', code: 'Digit1', keyCode: 49, shiftKey: true },
  '@': { key: '@', code: 'Digit2', keyCode: 50, shiftKey: true },
  '#': { key: '#', code: 'Digit3', keyCode: 51, shiftKey: true },
  '$': { key: '$', code: 'Digit4', keyCode: 52, shiftKey: true },
  '%': { key: '%', code: 'Digit5', keyCode: 53, shiftKey: true },
  '^': { key: '^', code: 'Digit6', keyCode: 54, shiftKey: true },
  '&': { key: '&', code: 'Digit7', keyCode: 55, shiftKey: true },
  '*': { key: '*', code: 'Digit8', keyCode: 56, shiftKey: true },
  '(': { key: '(', code: 'Digit9', keyCode: 57, shiftKey: true },
  ')': { key: ')', code: 'Digit0', keyCode: 48, shiftKey: true },
  '_': { key: '_', code: 'Minus', keyCode: 189, shiftKey: true },
  '+': { key: '+', code: 'Equal', keyCode: 187, shiftKey: true },
  '{': { key: '{', code: 'BracketLeft', keyCode: 219, shiftKey: true },
  '}': { key: '}', code: 'BracketRight', keyCode: 221, shiftKey: true },
  ':': { key: ':', code: 'Semicolon', keyCode: 186, shiftKey: true },
  '"': { key: '"', code: 'Quote', keyCode: 222, shiftKey: true },
  '|': { key: '|', code: 'Backslash', keyCode: 220, shiftKey: true },
  '<': { key: '<', code: 'Comma', keyCode: 188, shiftKey: true },
  '>': { key: '>', code: 'Period', keyCode: 190, shiftKey: true },
  '?': { key: '?', code: 'Slash', keyCode: 191, shiftKey: true },

  // Пробел
  ' ': { key: ' ', code: 'Space', keyCode: 32 },
};